# Generated by Django 3.2.5 on 2021-08-16 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='type',
            field=models.CharField(choices=[('CREATE', 'Create'), ('READ', 'Read'), ('UPDATE', 'Update'), ('DELETE', 'Delete'), ('VISIBLE', 'Visible'), ('PRINT', 'Print')], default='READ', max_length=10),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id_dsd',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id_ssd',
            field=models.IntegerField(blank=True),
        ),
    ]
