# Generated by Django 3.2.5 on 2021-08-16 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iamapi', '0002_auto_20210816_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='role_id_dsd',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='role',
            name='role_id_ssd',
            field=models.IntegerField(null=True),
        ),
    ]
